### ISSUE TITLE
[Users] Admin User Management

### ISSUE THREAD

**Issue by skosman** [seng499-company2/back-end#18]
**Description:**
As the front end
I need to let the admin manage prof user creation
so that an admin that view, create, update, and delete prof users.   

**AC:**
When the front end hits the _GET users/_ endpoint, the back end will return all profs within the system. 

When the front end hits the _POST users/_ end point, the back end will create a new professor user record with associated username and password. (need to confirm what info will be created)

When the front end hits the _POST users/{professor-id}_ endpoint, the back end will update the professor's record with the corresponding id. 

When the front end hits the _DELETE users/{professor-id}_ endpoint, the back end delete the professor's record with the corresponding id. 
 
**Extra notes:**
Need to confirm what data will be needed to create a user and what data can be modified.

**Comment by rbassot** [comment]
The initial /users model (AppUser) is extending off of Django's native auth.User, to allow for easier authentication handling. There is no foreign key constraint between AppUser child and the auth.User parent, due to the way Django handles the FK:



![Image](https://user-images.githubusercontent.com/59449281/172028383-bf9e5533-0af3-4480-8276-135b4e0a5811.png)

**Comment by rbassot** [comment]
Russ and Kunal will help out with this ticket - Russ will look at views.py, Kunal will look at urls.py.

**Comment by rbassot** [comment]
Moved this ticket to Sprint2 as active until we are happy with the authentication/authorization work.
